apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-sla-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'oncall-prober'
        static_configs:
          - targets: ['oncall-prober-service:8000']  # Адрес нашего сервиса пробера
      - job_name: 'script-sla'
        static_configs:
          - targets: ['script-sla-service:8001']  # Адрес нашего SLA сервиса
