apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest  # Используем официальный образ Prometheus
        ports:
        - containerPort: 9090  # Порт, на котором будет доступен Prometheus
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
          subPath: prometheus.yml
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config  # Используем ранее созданный ConfigMap
