apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script-prober
  template:
    metadata:
      labels:
        app: script-prober
    spec:
      containers:
      - name: script-prober
        image: script-prober:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: script-prober-volume
          mountPath: /app/oncall_prober.py
          subPath: oncall_prober.py
      volumes:
      - name: script-prober-volume
        configMap:
          name: script-prober-config
