apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-sla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script-sla
  template:
    metadata:
      labels:
        app: script-sla
    spec:
      containers:
      - name: script-sla
        image: script-sla:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: script-sla-volume
          mountPath: /app/script_sla.py
          subPath: script_sla.py
      volumes:
      - name: script-sla-volume
        configMap:
          name: script-sla-config
