apiVersion: v1
kind: Service
metadata:
  name: oncall-prober-service
spec:
  selector:
    app: oncall-prober
  ports:
  - protocol: TCP
    port: 8000  # Порт, на котором доступен сервис
    targetPort: 8000
  type: ClusterIP  # Сервис доступен внутри кластера Minikube
